# train_classifier.py
# Offline training script. Run this once after data_gen.py finishes.
#
# What it does (in order):
#   1. Load training_data.jsonl (generated by data_gen.py)
#   2. Apply false positive corrections from ChromaDB (if any exist)
#   3. Encode all actions with all-MiniLM-L6-v2 (one-time, cached in RAM)
#   4. Train the PyTorch NN for 20 epochs with 80/20 train/val split
#   5. Print val accuracy + confusion matrix each epoch
#   6. Save the best weights (lowest val loss) to classifier_model.pt
#
# Why save best val loss rather than final epoch?
#   Training loss drops monotonically. Val loss may start rising after peak
#   (overfitting). Saving best val loss gives the most generalizable model.
#
# Usage:
#   python train_classifier.py
#   python train_classifier.py --data training_data.jsonl --epochs 30

import argparse
import json
import sys
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, random_split
from sentence_transformers import SentenceTransformer

from config import (
    EMBEDDING_MODEL,
    DATA_GEN_OUTPUT,
    CLASSIFIER_MODEL_PATH,
    MIN_TRAINING_SAMPLES,
)
from classifier import _RiskNet


def load_jsonl(path: str, fp_actions: set[str]) -> tuple[list[str], list[int]]:
    """
    Read training_data.jsonl, flip FP labels from 1→0.

    fp_actions: set of action strings the user marked as false positives.
                These were blocked but are actually safe — relabel them 0.
    """
    actions, labels = [], []
    skipped = 0
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                action = obj["action"]
                label = int(obj["label"])
                if label not in (0, 1):
                    skipped += 1
                    continue
                # Apply false positive correction
                if action in fp_actions and label == 1:
                    label = 0
                actions.append(action)
                labels.append(label)
            except (json.JSONDecodeError, KeyError):
                skipped += 1
    if skipped:
        print(f"  Skipped {skipped} malformed lines.")
    return actions, labels


def get_false_positives() -> set[str]:
    """
    Load false positive action strings from ChromaDB.
    Returns empty set if memory module or collection is unavailable.
    This is a best-effort correction — training proceeds even if ChromaDB is down.
    """
    try:
        import memory as mem_mod
        store = mem_mod.MemoryStore()
        return set(store.get_false_positives())
    except Exception as e:
        print(f"  Warning: could not load false positives from ChromaDB: {e}")
        return set()


def main():
    parser = argparse.ArgumentParser(description="Train the PyTorch risk classifier.")
    parser.add_argument("--data", default=DATA_GEN_OUTPUT, help="Path to training JSONL file.")
    parser.add_argument("--output", default=CLASSIFIER_MODEL_PATH, help="Where to save the model.")
    parser.add_argument("--epochs", type=int, default=20, help="Training epochs (default: 20).")
    parser.add_argument("--batch-size", type=int, default=64, help="Batch size (default: 64).")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate (default: 0.001).")
    parser.add_argument("--val-split", type=float, default=0.2, help="Validation fraction (default: 0.2).")
    args = parser.parse_args()

    data_path = Path(args.data)
    if not data_path.exists():
        print(f"ERROR: {data_path} not found. Run data_gen.py first.", file=sys.stderr)
        sys.exit(1)

    # ── Step 1: Load data ────────────────────────────────────────────────────
    print("Loading false positive corrections from ChromaDB...")
    fp_actions = get_false_positives()
    print(f"  {len(fp_actions)} false positive corrections loaded.")

    print(f"\nLoading training data from {data_path}...")
    actions, labels = load_jsonl(str(data_path), fp_actions)
    n = len(actions)
    print(f"  {n:,} samples loaded. Label distribution: "
          f"{labels.count(1):,} block ({100*labels.count(1)/n:.1f}%), "
          f"{labels.count(0):,} allow ({100*labels.count(0)/n:.1f}%)")

    if n < MIN_TRAINING_SAMPLES:
        print(f"ERROR: Only {n} samples. Need at least {MIN_TRAINING_SAMPLES}.", file=sys.stderr)
        sys.exit(1)

    # ── Step 2: Encode ───────────────────────────────────────────────────────
    print(f"\nEncoding {n:,} actions with {EMBEDDING_MODEL}...")
    print("  (This takes ~30–60s on CPU for 10,000 samples)")
    encoder = SentenceTransformer(EMBEDDING_MODEL)
    embeddings = encoder.encode(actions, batch_size=128, show_progress_bar=True, convert_to_tensor=True)
    label_tensor = torch.tensor(labels, dtype=torch.float32)

    # ── Step 3: Train/val split ──────────────────────────────────────────────
    dataset = TensorDataset(embeddings.cpu(), label_tensor)
    val_size = int(len(dataset) * args.val_split)
    train_size = len(dataset) - val_size
    train_ds, val_ds = random_split(dataset, [train_size, val_size])

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=256, shuffle=False)

    print(f"\nTrain: {train_size:,} samples | Val: {val_size:,} samples")

    # ── Step 4: Build model + optimizer ─────────────────────────────────────
    model = _RiskNet(input_dim=384)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    criterion = nn.BCELoss()

    best_val_loss = float("inf")
    best_state = None

    print(f"\nTraining for {args.epochs} epochs (batch_size={args.batch_size}, lr={args.lr})...")
    print(f"{'Epoch':>6} {'Train Loss':>11} {'Val Loss':>9} {'Val Acc':>8} {'TP':>6} {'FP':>6} {'TN':>6} {'FN':>6}")
    print("-" * 70)

    for epoch in range(1, args.epochs + 1):
        # --- Training pass ---
        model.train()
        train_loss_sum = 0.0
        for xb, yb in train_loader:
            optimizer.zero_grad()
            preds = model(xb).squeeze(1)
            loss = criterion(preds, yb)
            loss.backward()
            optimizer.step()
            train_loss_sum += loss.item() * len(xb)

        train_loss = train_loss_sum / train_size

        # --- Validation pass ---
        model.eval()
        val_loss_sum = 0.0
        tp = fp = tn = fn = 0

        with torch.no_grad():
            for xb, yb in val_loader:
                preds = model(xb).squeeze(1)
                loss = criterion(preds, yb)
                val_loss_sum += loss.item() * len(xb)

                predicted = (preds >= 0.5).float()
                tp += ((predicted == 1) & (yb == 1)).sum().item()
                fp += ((predicted == 1) & (yb == 0)).sum().item()
                tn += ((predicted == 0) & (yb == 0)).sum().item()
                fn += ((predicted == 0) & (yb == 1)).sum().item()

        val_loss = val_loss_sum / val_size
        val_acc = (tp + tn) / val_size * 100

        print(f"{epoch:>6} {train_loss:>11.4f} {val_loss:>9.4f} {val_acc:>7.2f}% "
              f"{int(tp):>6} {int(fp):>6} {int(tn):>6} {int(fn):>6}")

        # Save best checkpoint
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {k: v.clone() for k, v in model.state_dict().items()}

    # ── Step 5: Save best weights ────────────────────────────────────────────
    output_path = Path(args.output)
    torch.save(best_state, output_path)
    print(f"\nBest model saved → {output_path}  (val loss: {best_val_loss:.4f})")

    # Final confusion matrix summary
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    print()
    print("Validation confusion matrix (final epoch):")
    print(f"  True Positives  (risky, correctly blocked): {int(tp):>6}")
    print(f"  False Positives (safe, incorrectly blocked): {int(fp):>6}")
    print(f"  True Negatives  (safe, correctly allowed):  {int(tn):>6}")
    print(f"  False Negatives (risky, incorrectly allowed): {int(fn):>6}")
    print()
    print(f"  Precision : {precision:.4f}")
    print(f"  Recall    : {recall:.4f}")
    print(f"  F1 Score  : {f1:.4f}")
    print()
    print("Next step: python main.py  (source='classifier' should appear for high-confidence actions)")


if __name__ == "__main__":
    main()
